config/routes.rb
Rails.application.routes.draw do
  resources :albums
  root "albums#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
    has_one_attached :image 
    has_many_attached :pictures
    has_rich_text :body

    def image_as_thumbnail
        return unless image.content_type.in?(%w[image/jpeg image/png])
        image.variant(resize_to_limit: [300, 300]).processed
    end

    def pictures_as_thumbnails
        pictures.map do |picture|
            picture.variant(resize_to_limit: [150, 150]).processed
        end
    end

    def picture_as_thumbnail(pic)
        pic.variant(resize_to_limit: [200, 200]).processed 
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:title, :body, :image, pictures: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Title:</strong>
    <%= album.title %>
  </p>

  <%= album.body %>
  <br>
  <% if album.image.content_type.in?(%w[image/jpeg image/png])%>
  <%= link_to image_tag(album.image_as_thumbnail),album.image if album.image.attached?%>
  <% end %>
  <hr>
  <% album.pictures.each do |picture|%>
    <%= link_to image_tag(album.picture_as_thumbnail(picture)), picture %>
  <% end %>
</div>

app/views/albums/_form.html.erb
<div class="container ">
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block; font-weight: bold;" %>
    <%= form.text_field :title %>
  </div>
 
 
  <div>
    <%= form.label :image,style: "display: block; font-weight: bold;"  %> 
    <%= form.file_field :image%>
  </div>

  <div>
    <%= form.label :pictures, style: "display: block; font-weight: bold;" %>
    <%= form.file_field :pictures, multiple: true%>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/albums/edit.html.erb
<div class="container">
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>
</div>

app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Albums</h1>

<div id="albums">
  <% @albums.each do |album| %>
    <%= render album %>
    <p>
      <%= link_to "Show this album", album %>
    </p>
  <% end %>
</div>

<%= link_to "New album", new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>

<div>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>
</div>
<br>
<div>
  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ActiveStorage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>